version: '3'

services:
  whatsapp-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./sessions:/app/sessions
    environment:
      - NODE_ENV=production
      - PORT=5000
      # Uncomment and set these if you want to add API authentication
      # - API_USERNAME=admin
      # - API_PASSWORD=your_secure_password